### ISSUE TITLE
Add any type of devices

### ISSUE THREAD

**Issue by HydrelioxGitHub** [bimbar/bluepy_devices#1]
Hi,

I've just discovered your project by reading some Home Assistant code and I find it very interesting.

I'm using HA and i would like to add some bluetooth devices support. Mainly Bluetooth speaker or bluetooth smartbulb. Is your project only for Thermostat or are you open to include other kind of devices via PR ?

Thanks

**Comment by bimbar** [comment]
This is aimed to support any kind of BTLE device. So if you want to use it, feel free to do a PR for something.
